server:
  port: 8095
  tomcat:
    basedir: ${spring.application.name}/tomcat
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
      pattern: "%h %l %u %t %r %s %b %D"
      file-date-format: ".yyyy-MM-dd"
      rename-on-rotate: true
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
